"""Renders docs/DATA_CARD.md from a calibration artifact (so the documentation can never drift from the numbers)."""
from __future__ import annotations


def render(a: dict) -> str:
    h, n, q, r, m = a["headline"], a["network"], a["meta"]["quality"], a["review"], a["meta"]
    lines = [
        "# Data card — Olist calibration", "",
        f"_Generated by `scripts/build_calibration.py` (ETL v{m['etl_version']}, {m['built_at']}, checksum `{m['checksum'][:16]}`). Do not edit by hand._", "",
        "## Source", "", "Brazilian E-Commerce Public Dataset by Olist (9 CSVs). Raw files are **not** committed; only the distilled artifact is.", "",
        "| File | Rows | SHA-256 |", "|---|---:|---|",
        *[f"| `{v['file']}` | {v['rows']:,} | `{v['sha256'][:16]}…` |" for v in m["source_files"].values()], "",
        "## What was kept", "",
        f"- Raw orders: **{q['orders_raw']:,}**; analysed after cleaning: **{q['orders_analysed']:,}** ({h['date_from']} → {h['date_to']}).",
        f"- Dropped (all counted): multi-seller {q['multi_seller_dropped']:,}; not delivered / no delivery timestamp {q['not_delivered_dropped']:,}; "
        f"non-positive duration {q['non_positive_duration_dropped']:,}; unknown state {q['unknown_state_dropped']:,}.",
        f"- Carrier hand-off timestamp unusable (transit time unavailable): {q['carrier_timestamp_unusable']:,} orders.",
        f"- Products with missing weight / volume (filled with category median): {q['products_missing_weight']} / {q['products_missing_volume']}.",
        f"- Orders without a zip-to-zip distance (fall back to state centroids): {q['orders_without_zip_distance']:,}.",
        f"- Payments reconcile with items + freight (±R$1) for **{q['payment_reconciles_pct']}%** of orders.",
        f"- Lateness definition: {m['late_definition']}.", "",
        "## Headline measurements", "",
        "| Measure | Value |", "|---|---:|",
        f"| Orders crossing a state line | {h['cross_state_share']:.1%} |",
        f"| Freight premium, cross-state vs same-state (per order / per item) | +{h['freight_premium_order_pct']}% / +{h['freight_premium_item_pct']}% |",
        f"| Average freight / average merchandise value | R$ {h['avg_freight']} / R$ {h['avg_order_value']} ({h['freight_share_of_value_pct']}% of value) |",
        f"| Late-delivery rate vs customer promise | {h['late_rate']:.1%} (median {h['late_days_median']} days late when late) |",
        f"| Review score on-time → late | {r['on_time']:.2f} → {r['late']:.2f} (n = {r['n_on_time']:,} / {r['n_late']:,}) |",
        f"| Median delivery time vs median promise | {n['total_p50']} d vs {n['promised_p50']} d (promise is {n['sla_padding_ratio']}× the median) |",
        f"| Median seller handling / carrier transit | {n['handling_days_p50']} d / {n['transit_p50']} d (p90 {n['transit_p90']} d) |", "",
        "## How the data is used", "",
        "1. **Demand and supply geography** — real origin/destination state shares replace the hand-made weights.",
        "2. **Real order bootstrap** — a 20,000-order sample (joint origin, destination, month, weight, volume, value, category, promise) feeds model training, the Digital Twin and demo replay.",
        "3. **Route physics** — per-route real carrier-transit medians scale every simulated carrier's transit time; per-route late-rate relative to the network sets route risk; real zip-to-zip distances replace centroid distances.",
        "4. **Seasonality** — observed monthly lateness above the network mean (this includes Nov-2017 *and* the Feb–Mar 2018 disruption).",
        "5. **Tariffs** — simulated carrier prices are scaled per destination region so their median equals observed Olist freight for comparable orders.",
        "6. **Business impact** — review-score penalty for late delivery.",
        "7. **Benchmark** — carrier-agnostic ETA and late-risk models trained on real orders and scored on a chronological hold-out.", "",
        "## Limits (read before quoting numbers)", "",
        "- Olist publishes **no carrier identifier**. Carrier-level behaviour (prices, speeds, reliability, capacity) remains simulated behind the adapter contract; the real data constrains the *routes* and *market* those carriers operate in.",
        "- The customer promise in Olist data is heavily padded, which is why the late rate is low. The benchmark therefore measures predictability of marketplace outcomes, not carrier quality.",
        "- Feb–Mar 2018 is a network-wide disruption period, not a stable seasonal pattern; treat its month penalties as stress scenarios.",
        "- Data ends Oct 2018; nothing here is live.", "",
    ]
    b = a.get("benchmark")
    if b:
        e, l, s = b["eta"], b["late"], b["split"]
        lines += ["## Real-data benchmark (chronological hold-out)", "",
                  f"Train: orders before {s['train_until']} ({s['n_train']:,}). Test: {s['test_from']} → {s['test_to']} ({s['n_test']:,}).", "",
                  "| Metric | Model | Baseline |", "|---|---:|---|",
                  f"| ETA MAE (days) | **{e['mae_days_model']}** | {e['mae_days_olist_estimate']} (Olist estimate) · {e['mae_days_train_median']} (constant median) |",
                  f"| Late-risk ROC-AUC | **{l['auc_model']}** | {l['auc_route_history']} (route history) · 0.50 (chance) |",
                  f"| Brier score | **{l['brier_model']}** | {l['brier_constant']} (constant) |",
                  f"| Late rate in riskiest decile | **{l['top_decile_late_rate']:.1%}** ({l['top_decile_lift']}× lift) | {l['base_rate_test']:.1%} overall |", "",
                  f"Olist's own estimate is biased by {e['olist_estimate_bias_days']:+} days on the hold-out (it over-promises conservatively).", ""]
    return "\n".join(lines)
